# Generated by Django 2.2.19 on 2021-03-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ManyToManyField(blank=True, related_name='test_project', to='newname.Test')),
                ('test1', models.ManyToManyField(related_name='test_test1', to='home.CustomText')),
            ],
        ),
    ]
